*** (1)
2003/07/28 10:33 Pacific Daylight Time [Broker,client] Traceback (most recent call last):
          File "C:\python22\Lib\site-packages\twisted\spread\banana.py", line 320, in dataReceived
            processed = cBanana.dataReceived(self.state, buffer, self.callExpressionReceived)
          File "C:\python22\Lib\site-packages\twisted\spread\banana.py", line 93, in callExpressionReceived
            self.expressionReceived(obj)
          File "C:\python22\Lib\site-packages\twisted\spread\pb.py", line 473, in expressionReceived
            method(*sexp[1:])
          File "C:\python22\Lib\site-packages\twisted\spread\pb.py", line 807, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "C:\python22\Lib\site-packages\twisted\spread\pb.py", line 821, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "C:\python22\Lib\site-packages\twisted\spread\flavors.py", line 118, in remoteMessageReceived
            state = method(*args, **kw)
          File "c:\python22\Lib\site-packages\buildbot\bot.py", line 128, in remote_startCommand
            d = self.command.startCommand()
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 58, in startCommand
            self.start()
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 351, in start
            return self.start2()
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 392, in start2
            self.doUpdate()
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 404, in doUpdate
            d = c.startCommand()
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 58, in startCommand
            self.start()
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 177, in start
            self.environ, self.dir, usePTY=0)
          File "C:\python22\Lib\site-packages\twisted\internet\default.py", line 168, in spawnProcess
            raise NotImplementedError, "process only available in this reactor on POSIX"
        exceptions.NotImplementedError: process only available in this reactor on POSIX



*** (2)
2003/07/28 10:34 Pacific Daylight Time [*buildslave-bot-w32*] Traceback (most recent call last):
          File "C:\python22\Lib\site-packages\twisted\spread\banana.py", line 320, in dataReceived
            processed = cBanana.dataReceived(self.state, buffer, self.callExpressionReceived)
          File "C:\python22\Lib\site-packages\twisted\spread\banana.py", line 93, in callExpressionReceived
            self.expressionReceived(obj)
          File "C:\python22\Lib\site-packages\twisted\spread\pb.py", line 473, in expressionReceived
            method(*sexp[1:])
          File "C:\python22\Lib\site-packages\twisted\spread\pb.py", line 807, in proto_message
            self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
        --- <exception caught here> ---
          File "C:\python22\Lib\site-packages\twisted\spread\pb.py", line 821, in _recvMessage
            netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
          File "C:\python22\Lib\site-packages\twisted\spread\flavors.py", line 116, in remoteMessageReceived
            method = getattr(self, "remote_%s" % message)
        exceptions.AttributeError: Bot instance has no attribute 'remote_getSlaveInfo'


*** (3)
2003/07/28 10:37 Pacific Daylight Time [*buildslave-bot-w32*]   command 'cvs -z3 update -r HEAD -dP' in dir C:\cygwin\home\cory\bot-w32\W32-full2.2\Twisted [Non
e]
2003/07/28 10:37 Pacific Daylight Time [*buildslave-bot-w32*] Traceback (most recent call last):
          File "C:\python22\Lib\site-packages\twisted\python\context.py", line 53, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "C:\python22\Lib\site-packages\twisted\python\context.py", line 32, in callWithContext
            return func(*args,**kw)
          File "C:\python22\Lib\site-packages\twisted\internet\default.py", line 122, in run
            self.mainLoop()
          File "C:\python22\Lib\site-packages\twisted\internet\default.py", line 133, in mainLoop
            self.doIteration(t)
        --- <exception caught here> ---
          File "C:\python22\Lib\site-packages\twisted\internet\win32eventreactor.py", line 200, in doWaitForMultipleEvents
            closed = action()
          File "C:\python22\Lib\site-packages\twisted\internet\default.py", line 346, in doRead
            self.r.recv(8192)
          File "<string>", line 1, in recv
        socket.error: (10035, 'The socket operation could not complete without blocking')

*** (4)
2003/07/28 10:38 Pacific Daylight Time [*buildslave-bot-w32*] Traceback (most recent call last):
          File "C:\python22\Lib\site-packages\twisted\python\context.py", line 53, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)

          File "C:\python22\Lib\site-packages\twisted\python\context.py", line 32, in callWithContext
            return func(*args,**kw)
          File "C:\python22\Lib\site-packages\twisted\internet\default.py", line 122, in run
            self.mainLoop()
          File "C:\python22\Lib\site-packages\twisted\internet\default.py", line 130, in mainLoop
            self.runUntilCurrent()
        --- <exception caught here> ---
          File "C:\python22\Lib\site-packages\twisted\internet\base.py", line 406, in runUntilCurrent
            callable(*args, **kw)
          File "C:\python22\Lib\site-packages\twisted\internet\win32eventreactor.py", line 344, in errConnectionLost
            self.connectionLostNotify()
          File "C:\python22\Lib\site-packages\twisted\internet\win32eventreactor.py", line 362, in connectionLostNotify
            self.connectionLost()
          File "C:\python22\Lib\site-packages\twisted\internet\win32eventreactor.py", line 373, in connectionLost
            self.protocol.processEnded(failure.Failure(err))
          File "c:\python22\Lib\site-packages\buildbot\slavecommand.py", line 104, in processEnded
            if os.WIFEXITED(s):
        exceptions.AttributeError: 'module' object has no attribute 'WIFEXITED'
