	Traceback (most recent call last):
	  File "/usr/lib/python2.6/dist-packages/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/lib/python2.6/dist-packages/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/ssh/channel.py", line 137, in requestReceived
	    return f(data)
	--- <exception caught here> ---
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/ssh/session.py", line 51, in request_shell
	    self.session.openShell(pp)
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/manhole_ssh.py", line 74, in openShell
	    self.width, self.height)
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/manhole_ssh.py", line 51, in __init__
	    name="Chained Proto Transport"))
	  File "/usr/lib/python2.6/dist-packages/twisted/internet/protocol.py", line 349, in makeConnection
	    self.connectionMade()
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/insults/insults.py", line 423, in connectionMade
	    self.terminalProtocol.makeConnection(self)
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/insults/insults.py", line 56, in makeConnection
	    self.connectionMade()
	  File "window.tac", line 119, in connectionMade
	    vp2 = window.ScrolledArea(t4)
	  File "/usr/lib/python2.6/dist-packages/twisted/conch/insults/window.py", line 733, in __init__
	    Widget.__init__(self, containee)
	exceptions.TypeError: object.__init__() takes no parameters
