2004/07/08 11:57 CEST [HTTPChannel,0,127.0.0.1] 127.0.0.1 - - [08/Jul/2004:09:57:55 +0000] "GET / HTTP/1.1" 200 2787 "-" "Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686) Opera 7.52  [en]"
2004/07/08 11:57 CEST [HTTPChannel,2,127.0.0.1] userdb.tac:252: exceptions.UserWarning: URLOverlay.__call__ is deprecated; use add or replace instead
2004/07/08 11:57 CEST [HTTPChannel,2,127.0.0.1] 127.0.0.1 - - [08/Jul/2004:09:57:57 +0000] "GET /foo?action=delete HTTP/1.1" 200 729 "-" "Mozilla/4.0 (compatible; MSIE 6.0; X11; Linux i686) Opera 7.52  [en]"
2004/07/08 11:57 CEST [HTTPChannel,3,127.0.0.1] Traceback (most recent call last):
	  File "/home/doc/lib/python2.3/site-packages/twisted/internet/default.py", line 526, in doSelect
	    _logrun(selectable, _drdw, selectable, method, dict)
	  File "/home/doc/lib/python2.3/site-packages/twisted/python/log.py", line 65, in callWithLogger
	    callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/doc/lib/python2.3/site-packages/twisted/python/log.py", line 52, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/doc/lib/python2.3/site-packages/twisted/python/context.py", line 43, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/doc/lib/python2.3/site-packages/twisted/internet/default.py", line 535, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/home/doc/lib/python2.3/site-packages/twisted/internet/tcp.py", line 255, in doRead
	    return self.protocol.dataReceived(data)
	  File "/home/doc/lib/python2.3/site-packages/twisted/protocols/basic.py", line 229, in dataReceived
	    return self.rawDataReceived(data)
	  File "/home/doc/lib/python2.3/site-packages/twisted/protocols/http.py", line 1015, in rawDataReceived
	    self.allContentReceived()
	  File "/home/doc/lib/python2.3/site-packages/twisted/protocols/http.py", line 1006, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/home/doc/lib/python2.3/site-packages/twisted/protocols/http.py", line 552, in requestReceived
	    args.update(
	  File "/usr/lib/python2.3/cgi.py", line 301, in parse_multipart
	    line = headers['content-disposition']
	  File "/usr/lib/python2.3/rfc822.py", line 390, in __getitem__
	    return self.dict[name.lower()]
	exceptions.KeyError: 'content-disposition'
	
