robert@austin:~/Downloads$ python gmail.py
connected <twisted.mail.imap4.IMAP4Client instance at 0x2e66638>
logged in ([['CAPABILITY', 'IMAP4rev1', 'UNSELECT', 'LITERAL+', 'IDLE', 'NAMESPACE', 'QUOTA', 'ID', 'XLIST', 'CHILDREN', 'X-GM-EXT-1', 'UIDPLUS', 'COMPRESS=DEFLATE']], 'OK fetchsimplifiedbodyerror@gmail.com authenticated (Success)')
got mailbox {'EXISTS': 10, 'PERMANENTFLAGS': (), 'READ-WRITE': False, 'UIDNEXT': 11, 'FLAGS': ('\\Answered', '\\Flagged', '\\Draft', '\\Deleted', '\\Seen'), 'UIDVALIDITY': 640400248, 'RECENT': 0}
[Failure instance: Traceback: <class 'twisted.mail.imap4.IllegalServerResponse'>: ('Not enough arguments', ['UID', '10', 'BODY', [[['TEXT', 'PLAIN', ['CHARSET', 'UTF-8'], None, None, 'QUOTED-PRINTABLE', '10609', '289'], ['TEXT', 'HTML', ['CHARSET', 'UTF-8'], None, None, 'QUOTED-PRINTABLE', '31505', '519'], 'ALTERNATIVE'], 'MIXED']])
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/mail/imap4.py:2449:_defaultHandler
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/mail/imap4.py:378:finish
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py:318:callback
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py:424:_startRunCallbacks
--- <exception caught here> ---
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/internet/defer.py:441:_runCallbacks
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/mail/imap4.py:3654:_cbFetch
/usr/local/lib/python2.6/dist-packages/Twisted-10.1.0-py2.6-linux-x86_64.egg/twisted/mail/imap4.py:3621:_parseFetchPairs
]

