Lonestar ~/code/Twisted/trunk % sudo bin/twistd -no dns -rv
2011-10-20 09:21:23-0500 [-] Log opened.
2011-10-20 09:21:23-0500 [-] twistd 11.0.0+r32928 (/usr/bin/python 2.6.6) starting up.
2011-10-20 09:21:23-0500 [-] reactor class: twisted.internet.pollreactor.PollReactor.
2011-10-20 09:21:23-0500 [-] DNSServerFactory starting on 53
2011-10-20 09:21:23-0500 [-] DNSDatagramProtocol starting on 53
2011-10-20 09:21:23-0500 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x82f8dc8c>
2011-10-20 09:21:33-0500 [DNSDatagramProtocol (UDP)] A query from ('10.0.0.222', 55352)
2011-10-20 09:21:33-0500 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 38
2011-10-20 09:21:33-0500 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x8865df2c>
2011-10-20 09:21:33-0500 [-] (UDP Port 38 Closed)
2011-10-20 09:21:33-0500 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x8865df2c>
2011-10-20 09:21:33-0500 [DNSProtocol,client] Lookup found 31 records
2011-10-20 09:24:07-0500 [DNSProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File "/home/teratorn/code/Twisted/trunk/twisted/application/app.py", line 323, in runReactorWithLogging
            reactor.run()
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/base.py", line 1169, in run
            self.mainLoop()
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/base.py", line 1181, in mainLoop
            self.doIteration(t)
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/pollreactor.py", line 167, in doPoll
            log.callWithLogger(selectable, _drdw, selectable, fd, event)
        --- <exception caught here> ---
          File "/home/teratorn/code/Twisted/trunk/twisted/python/log.py", line 84, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/home/teratorn/code/Twisted/trunk/twisted/python/log.py", line 69, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/home/teratorn/code/Twisted/trunk/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/home/teratorn/code/Twisted/trunk/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/posixbase.py", line 594, in _doReadOrWrite
            self._disconnectSelectable(selectable, why, inRead)
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/posixbase.py", line 260, in _disconnectSelectable
            selectable.readConnectionLost(f)
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/tcp.py", line 257, in readConnectionLost
            self.connectionLost(reason)
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/tcp.py", line 433, in connectionLost
            Connection.connectionLost(self, reason)
          File "/home/teratorn/code/Twisted/trunk/twisted/internet/tcp.py", line 277, in connectionLost
            protocol.connectionLost(reason)
          File "/home/teratorn/code/Twisted/trunk/twisted/names/dns.py", line 1908, in connectionLost
            self.controller.connectionLost(self)
        exceptions.AttributeError: Resolver instance has no attribute 'connectionLost'
        
2011-10-20 09:24:26-0500 [DNSDatagramProtocol (UDP)] A query from ('10.0.0.222', 52907)
2011-10-20 09:24:26-0500 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 50370
2011-10-20 09:24:26-0500 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x88243c8c>
2011-10-20 09:24:26-0500 [-] (UDP Port 50370 Closed)
2011-10-20 09:24:26-0500 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x88243c8c>
2011-10-20 09:24:31-0500 [DNSDatagramProtocol (UDP)] A query from ('10.0.0.222', 52907)
2011-10-20 09:24:36-0500 [DNSDatagramProtocol (UDP)] A query from ('10.0.0.222', 52907)
2011-10-20 09:24:36-0500 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.names.error.DNSQueryTimeoutError: 
        
2011-10-20 09:24:36-0500 [-] Lookup failed
2011-10-20 09:24:36-0500 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.names.error.DNSQueryTimeoutError: 
        
2011-10-20 09:24:36-0500 [-] Lookup failed
2011-10-20 09:24:36-0500 [-] Unhandled Error
        Traceback (most recent call last):
        Failure: twisted.names.error.DNSQueryTimeoutError: 
        
2011-10-20 09:24:36-0500 [-] Lookup failed
^C2011-10-20 09:25:11-0500 [-] Received SIGINT, shutting down.
2011-10-20 09:25:11-0500 [-] (UDP Port 53 Closed)
2011-10-20 09:25:11-0500 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x82f8dc8c>
2011-10-20 09:25:11-0500 [-] (TCP Port 53 Closed)
2011-10-20 09:25:11-0500 [-] Main loop terminated.
2011-10-20 09:25:11-0500 [-] Server Shut Down.
