Index: twisted/test/test_defer.py
===================================================================
--- twisted/test/test_defer.py	(revision 32226)
+++ twisted/test/test_defer.py	(working copy)
@@ -966,8 +966,8 @@
         fail = l[0]
         self.assertEquals(fail.value, exc)
         localz, globalz = fail.frames[0][-2:]
-        self.assertEquals([], localz)
-        self.assertEquals([], globalz)
+        self.assertEqual([], list(localz))
+        self.assertEqual([], list(globalz))
 
 
     def test_errbackWithNoArgs(self):
@@ -988,8 +988,8 @@
         fail = l[0]
         self.assertEquals(fail.value, exc)
         localz, globalz = fail.frames[0][-2:]
-        self.assertNotEquals([], localz)
-        self.assertNotEquals([], globalz)
+        self.assertNotEqual([], list(localz))
+        self.assertNotEqual([], list(globalz))
 
 
     def test_errorInCallbackDoesNotCaptureVars(self):
@@ -1007,8 +1007,8 @@
         d.addErrback(l.append)
         fail = l[0]
         localz, globalz = fail.frames[0][-2:]
-        self.assertEquals([], localz)
-        self.assertEquals([], globalz)
+        self.assertEqual([], list(localz))
+        self.assertEqual([], list(globalz))
 
 
     def test_errorInCallbackCapturesVarsWhenDebugging(self):
@@ -1026,11 +1026,25 @@
         d.addErrback(l.append)
         fail = l[0]
         localz, globalz = fail.frames[0][-2:]
-        self.assertNotEquals([], localz)
-        self.assertNotEquals([], globalz)
+        self.assertNotEqual([], list(localz))
+        self.assertNotEqual([], list(globalz))
 
 
+    def test_immediateErrbackDoesNotResultInCleanedFailure(self):
+        d = defer.Deferred()
+        try:
+            1/0
+        except:
+            d.errback()
+        called = [False]
+        def err(fail):
+            called[0] = True
+            self.assertIsNot(fail.tb, None)
+        d.addErrback(err)
+        self.assertTrue(called[0])
 
+
+
 class FirstErrorTests(unittest.TestCase):
     """
     Tests for L{FirstError}.
Index: twisted/topfiles/3622.bugfix
===================================================================
--- twisted/topfiles/3622.bugfix	(revision 0)
+++ twisted/topfiles/3622.bugfix	(revision 0)
@@ -0,0 +1 @@
+Deferred._runCallbacks now doesn't alter its Failure when providing a cleaned Failure to its DebugInfo.
Index: twisted/internet/defer.py
===================================================================
--- twisted/internet/defer.py	(revision 32226)
+++ twisted/internet/defer.py	(working copy)
@@ -580,10 +580,12 @@
                 if isinstance(current.result, failure.Failure):
                     # Stash the Failure in the _debugInfo for unhandled error
                     # reporting.
-                    current.result.cleanFailure()
                     if current._debugInfo is None:
                         current._debugInfo = DebugInfo()
-                    current._debugInfo.failResult = current.result
+
+                    fail = failure.Failure(current.result)
+                    fail.cleanFailure()
+                    current._debugInfo.failResult = fail
                 else:
                     # Clear out any Failure in the _debugInfo, since the result
                     # is no longer a Failure.
